const { contextBridge, ipcRenderer } = require('electron')
contextBridge.exposeInMainWorld("api", {
    version: process.version,
    lastTime: (callback) => { ipcRenderer.on("lastTime", (_event, value) => { callback(value) }) },
    contentTmp: (callback) => { ipcRenderer.on("contentTmp", (_event, value) => { callback(value) }) },
    config: (callback) => { ipcRenderer.on("config", (_event, value) => { callback(value) }) },
    save: (callback) => { ipcRenderer.on("save", (_event) => { callback() }) },
    saveTmp: (callback) => { ipcRenderer.on("saveTmp", (_event) => { callback() }) },
    saveRes: (value) => { ipcRenderer.send("saveRes", value) },
    saveTmpRes: (value) => { ipcRenderer.send("saveTmpRes", value) },
    zoom: (value) => { ipcRenderer.send("zoom", value) },
    clear: (callback) => { ipcRenderer.on("clear", (_event) => { callback() }) },
    message: (callback) => { ipcRenderer.on("message", (_event, value) => { callback(value) }) },
    captionEdit: (value) => { ipcRenderer.send("captionEdit", value) },
    requestHistory: (params) => ipcRenderer.send("request-history", params),
    requestDayDetail: (date) => ipcRenderer.send("request-day-detail", date),
    onHistoryData: (callback) => ipcRenderer.on("history-data", (_event, value) => callback(value)),
    onDayDetail: (callback) => ipcRenderer.on("day-detail", (_event, value) => callback(value)),
    undoClear: (callback) => ipcRenderer.on("undoClear", (_event) => callback()),
    editCaption: (callback) => ipcRenderer.on("editCaption", (_event) => callback()),
    initTemplates: (callback) => ipcRenderer.on("init-templates", (_event, value) => { callback(value) }),
    saveTemplates: (templates) => ipcRenderer.send("save-templates", templates),
    loadTemplates: (callback) => ipcRenderer.on("load-templates", (_event, value) => { callback(value) }),
    selectImage: () => ipcRenderer.invoke('select-image'),
    updateImagePaths: (paths) => ipcRenderer.send('update-image-paths', paths),
    updateImageConfig: (config) => ipcRenderer.send('update-image-config', config),
})
